### ISSUE TITLE
drop into selected group

### ISSUE THREAD

**Issue by SteveLowman** [gacarrillor/CopyLayersAndGroupsToClipboard#1]
Thank you for publishing this. It works really well for versions at least up to QGIS 2.18.18, and I hope it may be for QGIS 3, too.

My suggestion is to make the pasted groups or layers drop into the selected layer group. Currently, they drop underneath all the other layers.

**Comment by gacarrillor** [comment]
Hi! 

Good to know you find the plugin useful. Good news for you, somebody included the Copy Layers and Groups idea into QGIS 3.x. It was actually added some days ago, so if you want to use it, you would need to install a very recent QGIS version. If you work on Windows, there is a version for today 9th of April at https://qgis.org/downloads/weekly/ 

Regards, 

Germán
